### ISSUE TITLE
Add Julia Seasons of Contributions?

### ISSUE THREAD

**Issue by Ayushk4** [kossiitkgp/Open-Source-Internships#3]
Refer https://discourse.julialang.org/t/julia-seasons-of-contributions-to-supplement-gsoc/23922

Stipend = 2000 USD

**Comment by Ayushk4** [comment]
Also, there was a summer of code programme by World Brain, Ping @berserker1 pls provide with details/link.
I also, recall someone sharing about the matplotlib internship with stipend. 
@thealphadollar ^

**Comment by berserker1** [comment]
yeah for world brain [this](https://www.notion.so/WorldBrain-Summer-of-Code-13a3b33050d34539a9f27c5ebbf6a3b0) is the link and [this](https://github.com/WorldBrain) the org's Github link.

**Comment by thealphadollar** [comment]
> Refer https://discourse.julialang.org/t/julia-seasons-of-contributions-to-supplement-gsoc/23922
> 
> Stipend = 2000 USD

Hey @Ayushk4 , Why do you think it should be added to the list? Will it help the students next year; as to me it seems a one time thing for Julia and there is no concrete plan for them to continue it next year. Also the selection procedure is through GSoC and hence there is no other way of application.

Do you think we should add it?

**Comment by Ayushk4** [comment]
Sounds Fair @thealphadollar, you call.

**Comment by thealphadollar** [comment]
> yeah for world brain [this](https://www.notion.so/WorldBrain-Summer-of-Code-13a3b33050d34539a9f27c5ebbf6a3b0) is the link and [this](https://github.com/WorldBrain) the org's Github link.

Dear @berserker1 , I think the WorldBrain Summer of Code is the name for the participation in GSoC with WorldBrain. If you read more, they tell about how to submit proposal in GSoC and other related information which conveys that the link you presented is their projects and information page for GSoC.

Please look and see if we should still add it.

**Comment by thealphadollar** [comment]
@Ayushk4 [John Hunter Matplotlib Summer Fellowship](https://numfocus.org/programs/john-hunter-technology-fellowship) has been added.
